# Generated by Django 3.2 on 2022-06-12 16:17

from django.db import migrations, models
import django.db.models.deletion
import prints.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_slug', models.SlugField(unique=True)),
                ('image_type', models.CharField(choices=[('.jpg', 'Jpeg'), ('.png', 'Png')], default='.jpg', max_length=4)),
                ('image', models.ImageField(upload_to=prints.models.product_image_path)),
                ('overlay_width', models.CharField(default='70%', max_length=5)),
                ('overlay_x_offset', models.CharField(default='15%', max_length=5)),
                ('overlay_y_offset', models.CharField(default='15%', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('variant_type', models.CharField(choices=[('CL', 'Colour'), ('SZ', 'Size')], default='SZ', max_length=2)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prints.category')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='prints.productimage')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('display_name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sku', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='prints.productimage')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prints.product')),
            ],
            options={
                'unique_together': {('product', 'name'), ('product', 'display_name')},
            },
        ),
    ]
