# Generated by Django 3.2 on 2022-06-04 18:01

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.upload_to)),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('number', models.IntegerField()),
                ('user_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='accounts.useraccount')),
            ],
        ),
    ]
