# Generated by Django 3.2 on 2022-06-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_drawing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='number',
            new_name='save_slot',
        ),
    ]
