# Generated by Django 3.2 on 2022-06-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_number_drawing_save_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='default_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
