# Generated by Django 3.2 on 2022-06-21 12:26

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220620_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDrawingCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=orders.models.upload_to_cache)),
                ('stripe_pid', models.CharField(default='', max_length=254)),
            ],
        ),
    ]
